name: Build resume
on:
  - push
jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ondrejsika/latex-build-github-action@master
        with:
          filename: ondrej_sika_resume.tex
      - run: mkdir -p pdf && mv ondrej_sika_resume.pdf pdf/
      - uses: ondrejsika/latex-build-github-action@master
        with:
          filename: sika.work/ondrej_sika_resume.tex
      - run: mkdir -p pdf && mv ondrej_sika_resume.pdf pdf/sika_work_resume.pdf
      - uses: actions/upload-artifact@v1
        with:
          name: resumes
          path: pdf/

