name: Build resume
on:
  - push
jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ondrejsika/latex-build-github-action@master
        with:
          filename: ondrej_sika_resume.tex
      - uses: ondrejsika/latex-build-github-action@master
        with:
          filename: sika.work/ondrej_sika_resume.tex
      - run: mkdir -p ondrej_sika_resume && mv ondrej_sika_resume.pdf ondrej_sika_resume/ && mv sika.work/ondrej_sika_resume.pdf ondrej_sika_resume/ondrej_sika_resume-sika_work.pdf
      - uses: actions/upload-artifact@v1
        with:
          name: resume
          path: ondrej_sika_resume/

